### ISSUE TITLE
UI: Create Wireframe

### ISSUE THREAD

**Issue by patybn3** [wat-the-duck/pollaris-surveys-client#6]
wireframe on how the page should look like

**Comment by hashbangash** [comment]
![IMG_3821](https://user-images.githubusercontent.com/22508682/76435452-62f54080-638d-11ea-925e-eb0a252bcb4f.jpg)
![IMG_3825](https://user-images.githubusercontent.com/22508682/76435476-68528b00-638d-11ea-8990-25da5a3d51d5.jpg)
![IMG_3822](https://user-images.githubusercontent.com/22508682/76435491-6d173f00-638d-11ea-9ea7-abefba33b9f0.jpg)
![IMG_3824](https://user-images.githubusercontent.com/22508682/76435580-8d46fe00-638d-11ea-88ca-ce6094a5dae4.jpg)
![IMG_3828](https://user-images.githubusercontent.com/22508682/76435607-98019300-638d-11ea-8e0a-d0e550e874c1.jpg)
![IMG_3827](https://user-images.githubusercontent.com/22508682/76435626-9cc64700-638d-11ea-978f-10e6397ab897.jpg)
