### ISSUE TITLE
UI: All API calls have success or failure messages

### ISSUE THREAD

**Issue by ethanstrominger** [wat-the-duck/pollaris-surveys-client#7]
Add success and failure message in UI

Edit: I believe this is done but it would be great for someone to test it! -Ash, Sat, 12:07pm

**Comment by ethanstrominger** [comment]
some transactions such as CREATE have no messages and other are small such as sign up.

**Comment by hashbangash** [comment]
I am interested in using a Bootstrap toast or snackbar for this for a stretch goal.

**Comment by hashbangash** [comment]
Closed with https://github.com/wat-the-duck/pollaris-surveys-client/pull/44
